trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  displayName: 'Setup Enviroment'
  inputs:
    versionSpec: '10.x'
    

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install Dependencies'
  workingDirectory: 'Frontend/income-viz-web'
  
- script: ng build --prod
  displayName: 'Build'
  workingDirectory: 'Frontend/income-viz-web'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: 'Frontend/income-viz-web/dist/'
    ArtifactName: 'web-app'
    publishLocation: 'Container'