trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Setup Enviroment'
  inputs:
    versionSpec: '10.x'
    
- script: npm install -g @angular/cli
  displayName: 'Install Dependencies 1'
  workingDirectory: 'Frontend/income-viz-web'

- script: npm install
  displayName: 'Install Dependencies 2'
  workingDirectory: 'Frontend/income-viz-web'

- script: ng build --prod
  displayName: 'Build'
  workingDirectory: 'Frontend/income-viz-web'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: 'Frontend/income-viz-web/dist/'
    ArtifactName: 'web-app'
    publishLocation: 'Container'